package lemon_unicode

Emoji :: enum u8 {
	No,
	Emoji,
	Presentation,
	Modifier,
	Modifier_Base,
	Component,
	Extended_Pictographic,
}

emoji_pages := []u8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 4, 5, 6, 7, 8,
	1, 9, 1, 10, 1, 1, 1, 1, 11, 1, 12, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 13, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 14, 15, 16, 17,
	18, 19, 20, 21, 22, 23, 24, 1, 25, 25, 25, 26, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 27, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
}

emoji_table := []Emoji{
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .Component, .No, .No, .No, .No, .No, .No, .Component, .No, .No, .No, .No, .No, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Component, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .Component, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .No, .No,
	.Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No,
	.Extended_Pictographic, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic,
	.Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No,
	.Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No,
	.No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No,
	.No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No,
	.No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Component, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component,
	.No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Component, .Component, .Component, .Component, .Component,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No,
	.No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No,
	.No, .Extended_Pictographic, .No, .Extended_Pictographic, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic,
	.Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .Extended_Pictographic, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component,
	.Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component,
	.Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component, .Component,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
	.No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No, .No,
}

emoji_from_rune :: proc(codepoint: rune) -> Emoji {
	page_number := int(codepoint) >> PAGE_SHIFT
	page_offset := int(codepoint) & (PAGE_SIZE - 1)
	return emoji_table[int(emoji_pages[page_number]) * PAGE_SIZE + page_offset]
}

_is_emoji :: proc(codepoint: rune, emoji: Emoji) -> bool {
	return emoji_from_rune(codepoint) == emoji
}

is_emoji_no :: proc(codepoint: rune) -> bool {
	return emoji_from_rune(codepoint) == .No
}

is_emoji_emoji :: proc(codepoint: rune) -> bool {
	return emoji_from_rune(codepoint) == .Emoji
}

is_emoji_presentation :: proc(codepoint: rune) -> bool {
	return emoji_from_rune(codepoint) == .Presentation
}

is_emoji_modifier :: proc(codepoint: rune) -> bool {
	return emoji_from_rune(codepoint) == .Modifier
}

is_emoji_modifier_base :: proc(codepoint: rune) -> bool {
	return emoji_from_rune(codepoint) == .Modifier_Base
}

is_emoji_component :: proc(codepoint: rune) -> bool {
	return emoji_from_rune(codepoint) == .Component
}

is_emoji_extended_pictographic :: proc(codepoint: rune) -> bool {
	return emoji_from_rune(codepoint) == .Extended_Pictographic
}
